### ISSUE TITLE
No group wheel on Raspbian

### ISSUE THREAD

**Issue by RoboSparrow** [awslabs/amazon-cloudwatch-publisher#14]
Firstly, thank you for providing a solution for small devices

Here is the problem:

* env: Raspbian GNU/Linux 10 (buster)
* file: [installers/install-rpi.bash](https://github.com/awslabs/amazon-cloudwatch-publisher/blob/master/installers/install-rpi.bash)
* problem: Raspian, like Debian has no group `wheel`

```bash
cat /etc/group | grep wheel
# nope...
```

[Debian docs](https://wiki.debian.org/SystemGroups#Other_System_Groups): wheel does not exist by default

Proposed solution: replace `wheel` with `sudo` group

**Comment by lordjabez** [comment]
@RoboSparrow Thanks for the suggestion. I think I can actually tweak the installer to support either one simultaneously. I'll take a look here in a few days.

**Comment by lordjabez** [comment]
@RoboSparrow I updated the Raspberry Pi installer to pick the `sudo` group if it exists, otherwise `wheel`. Hopefully that works for you. Give it a try and let me know!

(also note I changed the name of the main branch to `main`)

**Comment by RoboSparrow** [comment]
@lordjabez, yepp - it works. Thank you!
