### ISSUE TITLE
Push Journal logs since begining

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [awslabs/amazon-cloudwatch-publisher#15]
I would like to propose a new feature.

Currently, the `amazon-cloudwatch-publisher` pushes the current logs from `journalctl` since the service starts, would it be possible to provide a configuration to push the journal logs from the beginning? Therefore we won't lose logs when the service is starting.

**Comment by lordjabez** [comment]
I like this idea! Will see if I can find some time to add it.

**Comment by lordjabez** [comment]
Hey @caiotoledo-lunasystems I adjusted the flags passed to `journalctl` so it now goes back to the beginning of the current boot. Thanks for the suggestion!
