### ISSUE TITLE
Auth via IoT X.509 certificates

### ISSUE THREAD

**Issue by mkozjak** [awslabs/amazon-cloudwatch-publisher#2]
Are there any plans to support authentication and publishing via [awsiot](https://github.com/aws/aws-iot-device-sdk-python-v2) mqtt_connection_builder?
This would come in handy for using on embedded devices that leverage AWS IoT Core to log all system stdout and stderr pipes before the aws iot client kicks in.

**Comment by lordjabez** [comment]
I hadn't considered that, but it's a great idea. I'm pretty swamped this week, but will take a look as soon as I can.

**Comment by lordjabez** [comment]
@mkozjak I just pushed an update that includes support for using AWS IoT X.509 auth to publish metrics and logs. Let me know what you think.

I also included a couple additional new features: ability to specify log retention, and support for filtering log lines using regexes.

**Comment by mkozjak** [comment]
Amazing, thank you!

**Comment by mkozjak** [comment]
@lordjabez, one additional question - is there a reason the implementation uses a concatenated file including cert and key while aws-iot-device-sdk-python-v2 uses separate files? We’d need to duplicate files on our devices to initiate auth. Any thoughts?

**Comment by lordjabez** [comment]
The implementation actually supports either separate cert/key files or a single file. I updated the documentation to indicate as much (and renamed the field in the config to make it more general).

**Comment by mkozjak** [comment]
Thank you so much, @lordjabez!

**Comment by henning-schild** [comment]
I am trying to get this to work on machines using the latest debian package from https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb

It almost looks like this package does not (yet?) support x509 authentication. Another fun fact is that it carries a newer version than mentioned in the changelog https://s3.amazonaws.com/amazoncloudwatch-agent/info/latest/RELEASE_NOTES

I am not sure i get the relationship between cloudwatchagent and amazon-cloudwatch-publisher, it the publisher a part of the agent, an addon or even a replacement?

**Comment by lordjabez** [comment]
This package is an alternative to Amazon Cloudwatch Agent. I wrote it initially because I needed to collect metrics on MacOS, which wasn't supported by the agent. You wouldn't use both.

If the agent works for your operating system and use case, that's what I'd recommend. But if you need a feature it doesn't have (like x509 auth) then amazon-cloudwatch-publisher is a good choice.
