### ISSUE TITLE
Support python3.5

### ISSUE THREAD

**Issue by cph-w** [awslabs/amazon-cloudwatch-publisher#3]
Python3.5 is end of life recently so I can understand if this issue is rejected and couldn't find from the documentation whether not supporting Python3.5 was an intentional choice.

After a brief review it looks like there are a few blockers to using this with python3.5 interpreter.

* Use of f-string: `url = f'https://{endpoint}/role-aliases/{role_alias}/credentials'`
* Use of subprocess.run keyword arguments `capture_output` and `encoding`: `subprocess.run(command, shell=True, capture_output=True, encoding='UTF-8')`

I currently have a patched version running successfully. If supporting python3.5 is desired I can open a pull request.

**Comment by lordjabez** [comment]
Given that Python 3.5 is EOL, I'm not keen to clutter the code with support for it, but am happy to take a look at your PR.

**Comment by lordjabez** [comment]
Not going to merge support for Python 3.5, but linked PR is available if anyone needs to make a manual edit.
