### ISSUE TITLE
Don't push empty log messages

### ISSUE THREAD

**Issue by cph-w** [awslabs/amazon-cloudwatch-publisher#4]
Empty log events fail validation leading to unnecessary errors. An empty readline produces an event with empty string `message`.

**Comment by lordjabez** [comment]
Good catch. I've written a PR to fix.

**Comment by lordjabez** [comment]
@cph-w Would you mind taking a quick look at the PRs I created to ensure they fix the issues you identified?

**Comment by cph-w** [comment]
@lordjabez had a look, they look good to me. Thanks for your work on this. I do have a competing PR for one of them, please just close if you prefer.

**Comment by lordjabez** [comment]
Fixed in PR #6
