### ISSUE TITLE
Continue log file iteration on error from one log file

### ISSUE THREAD

**Issue by cph-w** [awslabs/amazon-cloudwatch-publisher#5]
In `push_log_data()` an exception raised getting/putting log events for any log item in the table causes an exception to be raised which interrupts the iteration.

If a log file is rapidly producing log events with bad data then it will repeatedly having the same exception raised due to an error and the iteration will be continually interrupted at that file. In the case where the same file is handled repeatedly earlier than other items in the table this produces behaviour of building up log events for the others in the table.

**Comment by lordjabez** [comment]
Great catch (pun intended). PR is up to fix it.

**Comment by cph-w** [comment]
@lordjabez You're apparently faster than me! I opened my own PR with a similar fix, please feel free to close if you prefer your own patch.

https://github.com/awslabs/amazon-cloudwatch-publisher/pull/9

**Comment by lordjabez** [comment]
Fixed in PR #8
